# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/soc_riscv_v2/soc_riscv_v2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2 || ORIG_REF_NAME==soc_riscv_v2} -quiet] -quiet

# IP: bd/soc_riscv_v2/ip/soc_riscv_v2_processing_system7_0_0/soc_riscv_v2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2_processing_system7_0_0 || ORIG_REF_NAME==soc_riscv_v2_processing_system7_0_0} -quiet] -quiet

# IP: bd/soc_riscv_v2/ip/soc_riscv_v2_axi_gpio_0_0/soc_riscv_v2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2_axi_gpio_0_0 || ORIG_REF_NAME==soc_riscv_v2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/soc_riscv_v2/ip/soc_riscv_v2_axi_lutram_wrapper_0_0/soc_riscv_v2_axi_lutram_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2_axi_lutram_wrapper_0_0 || ORIG_REF_NAME==soc_riscv_v2_axi_lutram_wrapper_0_0} -quiet] -quiet

# IP: bd/soc_riscv_v2/ip/soc_riscv_v2_axi_lutram_wrapper_1_0/soc_riscv_v2_axi_lutram_wrapper_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2_axi_lutram_wrapper_1_0 || ORIG_REF_NAME==soc_riscv_v2_axi_lutram_wrapper_1_0} -quiet] -quiet

# IP: bd/soc_riscv_v2/ip/soc_riscv_v2_cpu_0_0/soc_riscv_v2_cpu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2_cpu_0_0 || ORIG_REF_NAME==soc_riscv_v2_cpu_0_0} -quiet] -quiet

# IP: bd/soc_riscv_v2/ip/soc_riscv_v2_axi_smc_0/soc_riscv_v2_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2_axi_smc_0 || ORIG_REF_NAME==soc_riscv_v2_axi_smc_0} -quiet] -quiet

# IP: bd/soc_riscv_v2/ip/soc_riscv_v2_rst_ps7_0_100M_0/soc_riscv_v2_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2_rst_ps7_0_100M_0 || ORIG_REF_NAME==soc_riscv_v2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/soc_riscv_v2/ip/soc_riscv_v2_calc_ip_0_0/soc_riscv_v2_calc_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2_calc_ip_0_0 || ORIG_REF_NAME==soc_riscv_v2_calc_ip_0_0} -quiet] -quiet

# IP: bd/soc_riscv_v2/ip/soc_riscv_v2_addr_decoder_0_0/soc_riscv_v2_addr_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_riscv_v2_addr_decoder_0_0 || ORIG_REF_NAME==soc_riscv_v2_addr_decoder_0_0} -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v2/soc_riscv_v2_ooc.xdc
