# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Vivado_projects/RISCV_SOC/RISCV_SOC.srcs/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/soc_riscv_v1_cpu_0_0.xci
# IP: The module: 'soc_riscv_v1_cpu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_arinsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_rinsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_awinsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_winsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_binsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_aroutsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_routsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_awoutsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_woutsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_boutsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_arni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_rni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_awni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_wni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_bni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_s00a2s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_sarn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_srn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_sawn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_swn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_sbn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00arn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00rn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00awn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00wn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00bn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01arn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01rn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01awn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01wn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01bn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02arn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02rn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02awn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02wn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02bn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Vivado_projects/RISCV_SOC/RISCV_SOC.srcs/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/soc_riscv_v1_cpu_0_0.xci
# IP: The module: 'soc_riscv_v1_cpu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_arinsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_rinsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_awinsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_winsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_binsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_aroutsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_routsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_awoutsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_woutsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_boutsw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_arni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_rni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_awni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_wni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_bni_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_s00a2s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_sarn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_srn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_sawn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_swn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_sbn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00arn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00rn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00awn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00wn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m00bn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01arn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01rn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01awn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01wn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m01bn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02arn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02rn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02awn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02wn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/bd_c97e_m02bn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Vivado_projects/RISCV_SOC/RISCV_SOC.gen/sources_1/bd/soc_riscv_v1/ip/soc_riscv_v1_cpu_0_0/src/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_riscv_v1_cpu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
